version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: ${POSTGRES_DB} # The PostgreSQL default database (automatically created at first launch)
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
  backend:
    image: gramo37/chessbet-backend:latest
    ports: 
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      BACKEND_PORT: ${BACKEND_PORT}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: "SECRET_KEY"
      NODE_ENV: ${NODE_ENV}
      WEBSOCKET_PORT: ${WEBSOCKET_PORT}
      VITE_WS_URL: ${VITE_WS_URL}
      REDIS_KEY: "REDIS_KEY"
      REDIS_DATA_KEY: "data"
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      INTASEND_PUBLISHABLE_KEY: ${INTASEND_PUBLISHABLE_KEY}
      INTASEND_SECRET_KEY: ${INTASEND_SECRET_KEY}
      INTASEND_IS_TEST: ${INTASEND_IS_TEST}
      INSTASEND_CURRENCY: ${INSTASEND_CURRENCY}
      INSTASEND_PLATFORM_PERCENT: ${INSTASEND_PLATFORM_PERCENT}
      CRYPTO_DEPOSIT_PERCENT: ${CRYPTO_DEPOSIT_PERCENT}
      CRYPTO_MERCHANT_ID: ${CRYPTO_MERCHANT_ID}
      CRYPTO_PAYMENT_API_KEY: ${CRYPTO_PAYMENT_API_KEY}
      CRYPTO_PAYOUT_API_KEY: ${CRYPTO_PAYOUT_API_KEY}
      CRYTPOMUS_URI: ${CRYTPOMUS_URI}
      BCRYPT_SECRET_KEY: ${BCRYPT_SECRET_KEY}
      INSTASEND_CHALLENGE: ${INSTASEND_CHALLENGE}
      BINANCE_SECRET_KEY: ${BINANCE_SECRET_KEY}
      BINANCE_API_KEY: ${BINANCE_API_KEY}
    depends_on:
      - redis
  ws:
    image: gramo37/chessbet-ws:latest
    ports: 
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      BACKEND_PORT: ${BACKEND_PORT}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: "SECRET_KEY"
      NODE_ENV: ${NODE_ENV}
      WEBSOCKET_PORT: ${WEBSOCKET_PORT}
      VITE_WS_URL: ${VITE_WS_URL}
      REDIS_KEY: "REDIS_KEY"
      REDIS_DATA_KEY: "data"
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      INTASEND_PUBLISHABLE_KEY: ${INTASEND_PUBLISHABLE_KEY}
      INTASEND_SECRET_KEY: ${INTASEND_SECRET_KEY}
      INTASEND_IS_TEST: ${INTASEND_IS_TEST}
      INSTASEND_CURRENCY: ${INSTASEND_CURRENCY}
      INSTASEND_PLATFORM_PERCENT: ${INSTASEND_PLATFORM_PERCENT}
      CRYPTO_DEPOSIT_PERCENT: ${CRYPTO_DEPOSIT_PERCENT}
      CRYPTO_MERCHANT_ID: ${CRYPTO_MERCHANT_ID}
      CRYPTO_PAYMENT_API_KEY: ${CRYPTO_PAYMENT_API_KEY}
      CRYPTO_PAYOUT_API_KEY: ${CRYPTO_PAYOUT_API_KEY}
      CRYTPOMUS_URI: ${CRYTPOMUS_URI}
      BCRYPT_SECRET_KEY: ${BCRYPT_SECRET_KEY}
    depends_on:
      - redis
  frontend:
    image: gramo37/chessbet-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - ws
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      BACKEND_PORT: ${BACKEND_PORT}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: "SECRET_KEY"
      NODE_ENV: ${NODE_ENV}
      WEBSOCKET_PORT: ${WEBSOCKET_PORT}
      VITE_WS_URL: ${VITE_WS_URL}
      REDIS_KEY: "REDIS_KEY"
      REDIS_DATA_KEY: "data"
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      INTASEND_PUBLISHABLE_KEY: ${INTASEND_PUBLISHABLE_KEY}
      INTASEND_SECRET_KEY: ${INTASEND_SECRET_KEY}
      INTASEND_IS_TEST: ${INTASEND_IS_TEST}
      INSTASEND_CURRENCY: ${INSTASEND_CURRENCY}
      INSTASEND_PLATFORM_PERCENT: ${INSTASEND_PLATFORM_PERCENT}
      CRYPTO_DEPOSIT_PERCENT: ${CRYPTO_DEPOSIT_PERCENT}
      CRYPTO_MERCHANT_ID: ${CRYPTO_MERCHANT_ID}
      CRYPTO_PAYMENT_API_KEY: ${CRYPTO_PAYMENT_API_KEY}
      CRYPTO_PAYOUT_API_KEY: ${CRYPTO_PAYOUT_API_KEY}
      CRYTPOMUS_URI: ${CRYTPOMUS_URI}
      BCRYPT_SECRET_KEY: ${BCRYPT_SECRET_KEY}